#!/bin/bash

C=$(kubectl get configMap -n livecloud -o json \
  | jq '.items[] | .metadata.name as $name | .data | with_entries(.key |= "          - name: " + . + "\n            valueFrom:\n              configMapKeyRef:\n                name: " + ($name) + "\n                key: " + .)' \
  | grep ":" | grep -i $1 | sed -r 's/\s+"(.*)": "(.*)",?$/\1/g')

OIFS=$IFS
IFS=
[[ -n $C ]] && echo -e $C
IFS=$OIFS

S=$(kubectl get secret -n livecloud -o json \
  | jq '.items[] | .metadata.name as $name | .data | with_entries(.key |= "          - name: " + . + "\n            valueFrom:\n              secretKeyRef:\n                name: " + ($name) + "\n                key: " + .)' \
  | grep ":" | grep -i $1 | sed -r 's/\s+"(.*)": "(.*)",?$/\1/g')

OIFS=$IFS
IFS=
[[ -n $S ]] && echo -e $S
IFS=$OIFS
