#!/bin/bash

C=$(kubectl get configMap -n livecloud -o json \
  | jq '.items[] | .metadata.name as $name | .data | with_entries(.key |= "# ConfigMap " + ($name) + "\n" + .)' \
  | grep ":" | grep -i $1 | sed -r 's/\s+"(.*)": "(.*)",?$/\1="\2"/g')

[[ -n $C ]] && echo -e $C

S=$(kubectl get secret -n livecloud -o json \
  | jq '.items[] | .metadata.name as $name | .data | with_entries(.key |= "# Secret " + ($name) + "\n" + .)' \
  | grep ":" | grep -i $1 | sed -r 's/\s+"(.*)": "(.*)",?$/\1:\2/g' \
  | awk -F: -v q="'" '{a="\""; cmd="echo -n " q $2 q " | base64 -d | tr -d [:cntrl:]";cmd| getline x;close(cmd); print $1 "=" q x q}')

[[ -n $S ]] && echo -e $S
